# Generated by Django 5.2.7 on 2026-05-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
